import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const projectRoot = path.resolve('super_sean_007_full_project_wired');
const outputRoot = path.join(projectRoot, 'assets', 'sliced');
const manifestPath = path.join(projectRoot, 'data', 'sliced-assets.json');

const plans = [
  ...['sean', 'dave', 'petroman', 'haraku', 'ruush'].map((id) => ({
    id,
    type: 'character',
    source: `assets/characters/${id}_strip.png`,
    output: `characters/${id}`,
    frameWidth: 88,
    frameHeight: 88,
    maxFrames: 10
  })),
  ...[
    ['slime', 'assets/characters/enemy_slime.png'],
    ['mushroom', 'assets/characters/enemy_mushroom.png'],
    ['bat', 'assets/characters/enemy_bat.png'],
    ['crystal', 'assets/characters/enemy_crystal.png'],
    ['xelar', 'assets/characters/xelar_portrait.png']
  ].map(([id, source]) => ({
    id,
    type: 'enemy',
    source,
    output: `enemies/${id}`,
    frameWidth: null,
    frameHeight: null,
    maxFrames: 1
  })),
  ...[
    'birthday_village_tiles',
    'mushroom_meadow_tiles',
    'crystal_cave_tiles',
    'petro_plains_tiles',
    'ruushwood_tiles',
    'moon_shrine_tiles',
    'ancient_ruins_tiles',
    'bald_moon_tower_tiles'
  ].map((id) => ({
    id,
    type: 'tileset',
    source: `assets/tilesets/${id}.png`,
    output: `tilesets/${id}`,
    frameWidth: 64,
    frameHeight: 64,
    maxFrames: 64
  })),
  {
    id: 'ui_hud_elements',
    type: 'ui',
    source: 'assets/generated/split_pack/12_ui_hud_elements.png',
    output: 'ui/hud',
    frameWidth: 112,
    frameHeight: 62,
    maxFrames: 28
  },
  {
    id: 'items_pickups',
    type: 'items',
    source: 'assets/generated/split_pack/17_chests_items_pickups.png',
    output: 'items/pickups',
    frameWidth: 49,
    frameHeight: 53,
    maxFrames: 24
  },
  {
    id: 'visual_effects',
    type: 'vfx',
    source: 'assets/generated/split_pack/19_visual_effects_vfx.png',
    output: 'vfx/effects',
    frameWidth: 58,
    frameHeight: 52,
    maxFrames: 24
  }
];

function rel(file) {
  return file.replaceAll('\\', '/');
}

await rm(outputRoot, { recursive: true, force: true });
await mkdir(outputRoot, { recursive: true });

const manifest = {
  generatedAt: 'deterministic-build',
  sourceNote: 'Generated by scripts/slice-assets.mjs. Original source sheets are preserved.',
  sheets: {},
  frames: []
};

for (const plan of plans) {
  const sourceAbs = path.join(projectRoot, plan.source);
  const metadata = await sharp(sourceAbs).metadata();
  const frameWidth = plan.frameWidth || metadata.width;
  const frameHeight = plan.frameHeight || metadata.height;
  const cols = Math.max(1, Math.floor(metadata.width / frameWidth));
  const rows = Math.max(1, Math.floor(metadata.height / frameHeight));
  const frameCount = Math.min(plan.maxFrames || cols * rows, cols * rows);
  const destDir = path.join(outputRoot, plan.output);
  await mkdir(destDir, { recursive: true });

  manifest.sheets[plan.id] = {
    type: plan.type,
    source: plan.source,
    frameWidth,
    frameHeight,
    sourceWidth: metadata.width,
    sourceHeight: metadata.height,
    frameCount,
    output: rel(path.relative(projectRoot, destDir))
  };

  for (let index = 0; index < frameCount; index += 1) {
    const col = index % cols;
    const row = Math.floor(index / cols);
    const file = path.join(destDir, `frame_${String(index).padStart(2, '0')}.png`);
    await sharp(sourceAbs)
      .extract({
        left: col * frameWidth,
        top: row * frameHeight,
        width: frameWidth,
        height: frameHeight
      })
      .png({ compressionLevel: 9, adaptiveFiltering: true })
      .toFile(file);
    manifest.frames.push({
      sheet: plan.id,
      type: plan.type,
      index,
      x: col * frameWidth,
      y: row * frameHeight,
      width: frameWidth,
      height: frameHeight,
      file: rel(path.relative(projectRoot, file))
    });
  }
}

await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Sliced ${manifest.frames.length} frames into assets/sliced and wrote data/sliced-assets.json`);
